name: Super Linter

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch: 

jobs:
  lint:
    name: Run Super Linter
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Run Super Linter
        uses: github/super-linter@v6
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_PYTHON_PYLINT: true
          VALIDATE_PYTHON_FLAKE8: true
          VALIDATE_GO: true
          VALIDATE_C: true
          VALIDATE_CLANG_FORMAT: true
          VALIDATE_CLANG_TIDY: true
          VALIDATE_CPP: true
          
          
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
