name: CI Full Check

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      #RUST
      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: clippy, rustfmt
          override: true

      - name: Build Rust
        continue-on-error: true
        run: cargo build --verbose

      - name: Lint Rust (Clippy)
        continue-on-error: true
        run: cargo clippy -- -D warnings

      - name: Test Rust
        continue-on-error: true
        run: cargo test

      # C++
      
      - name: Build C++
        continue-on-error: true
        run: g++ -Wall -Wextra -Werror -fsanitize=address -g test.cpp -o test_cpp

      - name: Run C++ binary
        continue-on-error: true
        run: ./test_cpp


      # C

      - name: Build C
        continue-on-error: true
        run: gcc -Wall -Wextra -Werror -fsanitize=address -g test.c -o test_c

      - name: Run C binary
        continue-on-error: true
        run: ./test_c


        #  GO

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Debug Go (optional but useful)
        run: |
          pwd
          ls -la
          find . -name go.mod

      - name: Build Go
        continue-on-error: true
        run: go build ./...

      - name: Vet Go (static analysis)
        continue-on-error: true
        run: go vet ./...

      - name: Test Go
        continue-on-error: true
        run: go test ./...

 


      # PYTHON

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        continue-on-error: true
        run: |
          pip install -r requirements.txt || true
          pip install pytest pylint flake8 black

      - name: Lint Python
        continue-on-error: true
        run: |
          pylint **/*.py || true
          flake8 . || true
          black --check . || true

      - name: Test Python
        continue-on-error: true
        run: pytest || true
